name: HA Camera Face ID
version: 2.2.0
slug: rtsp_face_bridge
description: Chọn camera entity từ Home Assistant, nhận diện khuôn mặt local bằng InsightFace và phát sự kiện MQTT.
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
homeassistant_api: true
ingress: true
ingress_port: 6868
panel_icon: mdi:face-recognition
ports:
  6868/tcp: 6868
ports_description:
  6868/tcp: HA Camera Face ID Web UI
webui: http://[HOST]:[PORT:6868]
options: {}
schema: {}
image: "ghcr.io/trankhanhduy2929-beep/rtsp_face_bridge"
url: "https://github.com/trankhanhduy2929-beep/my_hass_addon_public"
